/*ENTENDENDO O AUTO RELACIONAMENTO*/
CREATE TABLE FUNCIONARIOS
( 
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	NOME VARCHAR(100), 
	CHEFE INT REFERENCES FUNCIONARIOS(ID)
)

--INSERÇÃO DE GERENTES
INSERT INTO FUNCIONARIOS(NOME, CHEFE) VALUES
('GERENTE 1',NULL),
('GERENTE 2',NULL),
('GERENTE 3',NULL)

--INSERÇÃO DE ANALISTAS
INSERT INTO FUNCIONARIOS(NOME, CHEFE) VALUES
('ANALISTA 1',1),
('ANALISTA 2',2),
('ANALISTA 3',3)

--SELECT
SELECT * FROM FUNCIONARIOS

SELECT 
	F2.NOME,
	F1.NOME
FROM FUNCIONARIOS F1 (NOLOCK)
INNER JOIN FUNCIONARIOS F2 (NOLOCK) ON F1.ID = F2.CHEFE
