-- -----------------------------------------------------
-- DATABASE LOCADORA
-- -----------------------------------------------------
	USE MASTER
GO
	DROP DATABASE LOCADORA
GO
	CREATE DATABASE LOCADORA
GO
	USE LOCADORA
GO
-- -----------------------------------------------------
-- TABLE CATEGORIA
-- -----------------------------------------------------
GO
	CREATE TABLE CATEGORIA (
	COD_CATEGORIA   INT IDENTITY(1,1) NOT NULL,
	DESCRICAO		VARCHAR(50) NULL,
	PRIMARY KEY (COD_CATEGORIA) )
GO	
-- -----------------------------------------------------
-- TABLE CLIENTE
-- -----------------------------------------------------
GO
  CREATE  TABLE CLIENTE (
  COD_CLIENTE  INT IDENTITY(1,1) NOT NULL,
  NOME	VARCHAR(100) NULL DEFAULT NULL,
  TELEFONE VARCHAR(50) NULL DEFAULT NULL,
  CELULAR VARCHAR(50) NULL DEFAULT NULL,
  EMAIL VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (COD_CLIENTE) 
)
GO
-- -----------------------------------------------------
-- TABLE ENDERECO
-- -----------------------------------------------------
  CREATE  TABLE ENDERECO (
  COD_CLIENTE INT NOT NULL ,
  RUA VARCHAR(100) NULL DEFAULT NULL ,
  NUMERO INT NULL DEFAULT NULL ,
  BAIRRO VARCHAR(100) NULL DEFAULT NULL ,
  CIDADE VARCHAR(100) NULL DEFAULT NULL ,
  ESTADO CHAR(2) NULL DEFAULT NULL ,
  CEP VARCHAR(10) NULL DEFAULT NULL ,
  COMPLEMENTO TEXT NULL DEFAULT NULL ,  
  PRIMARY KEY (COD_CLIENTE) ,
  FOREIGN KEY (COD_CLIENTE ) REFERENCES CLIENTE (COD_CLIENTE)
  ON DELETE NO ACTION ON UPDATE CASCADE)
GO
--INDEX
CREATE INDEX FK_ENDERECO_COD_CLIENTE ON ENDERECO (COD_CLIENTE ASC)
GO
-- -----------------------------------------------------
-- TABLE FILME
-- -----------------------------------------------------
  CREATE  TABLE FILME (
  COD_FILME INT IDENTITY(1,1) NOT NULL ,
  COD_CATEGORIA INT NOT NULL ,
  DESCRICAO VARCHAR(50) NULL DEFAULT NULL ,
  ANO DATE NULL DEFAULT NULL ,
  PRIMARY KEY (COD_FILME) ,    
  FOREIGN KEY (COD_CATEGORIA )  REFERENCES CATEGORIA (COD_CATEGORIA )
  ON DELETE NO ACTION  ON UPDATE CASCADE)
GO
--INDEX
	CREATE INDEX FK_FILME_COD_CATEGORIA ON FILME (COD_CATEGORIA ASC)
GO
-- -----------------------------------------------------
-- TABLE MIDIA
-- -----------------------------------------------------
  CREATE  TABLE MIDIA (
  COD_MIDIA INT IDENTITY(1,1) NOT NULL ,
  COD_FILME INT NOT NULL ,
  INUTILIZADA CHAR(1) NULL DEFAULT NULL ,
  PRIMARY KEY (COD_MIDIA) ,    
  FOREIGN KEY (COD_FILME ) REFERENCES FILME (COD_FILME )
  ON DELETE NO ACTION ON UPDATE CASCADE)
GO
--INDEX
  CREATE INDEX FK_MIDIA_COD_FILME ON MIDIA (COD_FILME ASC)
GO
-- -----------------------------------------------------
-- TABLE LOCACAO
-- -----------------------------------------------------
  CREATE  TABLE LOCACAO (
  COD_LOCACAO INT IDENTITY(1,1) NOT NULL ,
  COD_CLIENTE INT NOT NULL ,
  COD_MIDIA INT NOT NULL ,
  DATA_EMPRESTIMO DATE NULL DEFAULT NULL ,
  HORA_EMPRESTIMO TIME NULL DEFAULT NULL ,
  DATA_DEVOLUCAO DATE NULL DEFAULT NULL ,
  OBS TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (COD_LOCACAO, COD_CLIENTE, COD_MIDIA) ,  
  FOREIGN KEY (COD_CLIENTE )   REFERENCES CLIENTE (COD_CLIENTE ),
  FOREIGN KEY (COD_MIDIA )  REFERENCES MIDIA (COD_MIDIA )
  ON DELETE NO ACTION ON UPDATE CASCADE)   
GO
--INDEX
  CREATE INDEX FK_LOCACAO_COD_CLIENTE ON LOCACAO (COD_CLIENTE ASC) 
  CREATE INDEX FK_LOCACAO_COD_MIDIA ON LOCACAO (COD_MIDIA ASC) 
GO
	USE LOCADORA