CREATE TABLE PRODUTS
(
	PRODUTID INT PRIMARY KEY,
	PRODUTNAME VARCHAR(100),
	RATE MONEY
)
GO
INSERT INTO PRODUTS
VALUES
	(1,'TEA',10.00),
	(2,'COFFE',20.00),
	(3,'MUFFIN',30.00),
	(4,'BISCUIT',40.00)

CREATE TABLE 
	UPDATEDPRODUTS
(
	PRODUTID INT PRIMARY KEY,
	PRODUTNAME VARCHAR(100),
	RATE MONEY
)
INSERT INTO 
	UPDATEDPRODUTS 
VALUES
	(1,'TEA',10.00),
	(2,'COFFE',25.00),
	(5,'BOLACHA',55.00),
	(4,'BISCUIT',60.00)
--SINCRONIZA AS DUAS TABELAS
MERGE 
	PRODUTS AS TARGET --DESTINO
USING 
	UPDATEDPRODUTS AS SOURCE --ORIGEM
ON (TARGET.PRODUTID = SOURCE.PRODUTID)
WHEN MATCHED THEN
	UPDATE SET TARGET.RATE = SOURCE.RATE
WHEN NOT MATCHED BY TARGET THEN
	INSERT(PRODUTID,PRODUTNAME,RATE)
	VALUES(SOURCE.PRODUTID,SOURCE.PRODUTNAME,SOURCE.RATE)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE;

	SELECT * FROM PRODUTS

	create index primario on produts (produtid)
	alter table primario drop index produtid
	drop index produts.

--ATUALIZA A ESTATISTACA DO INDICE 
UPDATE STATISTICS produts(PRIMARIO)
WITH FULLSCAN

select @@SPID
begin transaction
delete from PRODUTS
rollback
select * from PRODUTS

sp_lock 53
set loctimeout 

select @@LOCK_TIMEOUT
set lock_timeout  -1