CREATE TABLE FUNCIONARIO(
IDFUNCIONARIO INT,
NOME VARCHAR(50),
ENDERECO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
EMAIL VARCHAR(50),
DATANASCIMENTO DATETIME,
CONSTRAINT IDFUNCIONARIO PRIMARY KEY (IDFUNCIONARIO)
)
GO
INSERT INTO FUNCIONARIO VALUES
(5,'CARLOS DIA','AV.LAPA,121','ITU','SP','CARLAO@GMAIL.COM',1894-08-18),
(6,'ANA MARIA DA CUNHA','AV.SAO PAULO 388','ITU','SP','ANINHACUNHA@GMAIL.COM',12-04-1988),
(7,'CLAUDIO REGINA MARTINS','RUA HOLANDA,388','CAMPINAS','SP','CREGINA@GMAIL.COM',04-12-1988),
(8,'MARCELA TATHO','RUA BELGICA,89','CAMPINAS','SP','MARCTATHO@HOTMAIL.COM',09-11-1987),
(9,'JORGE LUIS RODRIGUES','AV.DA SAUDADE,1989','SAO PAULO','SP','JORGELUIZ@YAHOO.COM',05-05-1990),
(10,'ANA PAULO CAMARGO','RUA COSTA E SILVA,33','JUNDIAI','SP','APCAMARGO@GMAIL.COM',11-04-1991),
(11,'IVO CUNHA','AV.RAIO DE LUZ,100','CAMPINAS','SP','IVO@BOL.COM.BR',11-04-1987),
(12,'CARLOS LUIS DE SOUZA','RUA NICOLAU COELHO,22','SAO PAULO','SP','CLS@BOL.COM.BR',30-04-1988)
GO
SELECT * FROM FUNCIONARIO
GO
UPDATE FUNCIONARIO 
SET CIDADE = 'VALINHOS' WHERE CIDADE = 'ITU'
COMMIT
GO
SELECT IDFUNCIONARIO,EMAIL FROM FUNCIONARIO WHERE ESTADO = 'SP'
GO
DELETE FROM FUNCIONARIO WHERE IDFUNCIONARIO = 5
GO
SELECT * FROM FUNCIONARIO
GO
SELECT DISTINCT CIDADE,ESTADO FROM FUNCIONARIO 