CREATE DATABASE CONCESSIONARIA
GO
USE CONCESSIONARIA
GO
CREATE TABLE VEICULO (
CHASSI VARCHAR(17),
MARCA VARCHAR(10),
MODELO VARCHAR(20),
ANO_DE_FABRICACAO INT,
ANO_DO_MODELO INT,
COMBUSTIVEL CHAR
CONSTRAINT CHASSI PRIMARY KEY (CHASSI)
)
GO
SELECT * FROM VEICULO
GO
ALTER TABLE VEICULO
ADD VALOR MONEY
GO
SELECT * FROM VEICULO
GO
ALTER TABLE VEICULO
ADD MOTOR VARCHAR(20)
GO
SELECT * FROM VEICULO
GO
ALTER TABLE VEICULO
DROP COLUMN MOTOR
GO
CREATE INDEX MARCA_MODELO_INDEX
ON VEICULO(MARCA ASC, MODELO ASC)
GO
CREATE INDEX ANO_FABRICACAO_INDEX
ON VEICULO (ANO_DE_FABRICACAO DESC)
GO
DROP INDEX MARCA_MODELO_INDEX
ON VEICULO
GO
DROP TABLE VEICULO
GO
USE master
GO
DROP DATABASE CONCESSIONARIA
GO